core/src/main/java/com/netflix/conductor/core/events/ScriptEvaluator.java
Do not allow external binding.
Do not allow java scope
=> Inline task cleanup

common/src/main/java/com/netflix/conductor/common/metadata/workflow/StartWorkflowRequest.java, common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/service/WorkflowServiceImpl.java, core/src/test/java/com/netflix/conductor/service/WorkflowServiceTest.java, grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java, grpc/src/main/proto/model/startworkflowrequest.proto, grpc/src/main/proto/model/workflowsummary.proto
----
Please remember to run `./gradlew :conductor-java-sdk:spotlessApply` to fix any format violations.
----
When starting a workflow `createdBy` is persisted.
=> When starting a workflow `createdBy` is persisted.

core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
----
----
Quick and dirty fix for a NPE in `orkes-conductor`. This issue happens only when running `orkes-conductor` on top of this conductor version.
=> Fix NPE in orkes conductor

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
----
Please remember to run `./gradlew :conductor-java-sdk:spotlessApply` to fix any format violations.
----
Issue #
----
=> Improve the performance of the check workflow complete method

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java
----
performance improvements
Please remember to run `./gradlew :conductor-java-sdk:spotlessApply` to fix any format violations.
----
Issue #
----
=> Performance improvements

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java
----
decider to return workflow model
Please remember to run `./gradlew :conductor-java-sdk:spotlessApply` to fix any format violations.
----
Issue #
----
=> Decider return workflow

core/build.gradle, core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java, core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java, core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowSweeper.java, core/src/test/java/com/netflix/conductor/core/dal/ExecutionDAOFacadeTest.java, core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java, core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java, core/src/test/java/com/netflix/conductor/core/metadata/MetadataMapperServiceTest.java, test-harness/build.gradle, test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy, test-harness/src/test/groovy/com/netflix/conductor/test/integration/ForkJoinSpec.groovy, test-harness/src/test/groovy/com/netflix/conductor/test/integration/NestedForkJoinSubWorkflowSpec.groovy, test-harness/src/test/java/com/netflix/conductor/test/integration/grpc/GrpcEndToEndTest.java, test-harness/src/test/java/com/netflix/conductor/test/integration/http/HttpEndToEndTest.java
=> Decider v2

core/src/main/java/com/netflix/conductor/core/config/ConductorCoreConfiguration.java, core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/DoWhileTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/DynamicTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/EventTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/ExclusiveJoinTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinDynamicTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/ForkJoinTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/HTTPTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/HumanTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/InlineTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/JoinTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/JsonJQTransformTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/KafkaPublishTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/LambdaTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/SetVariableTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/SimpleTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/StartWorkflowTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/TaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/TerminateTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/UserDefinedTaskMapper.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/WaitTaskMapper.java, core/src/test/java/com/netflix/conductor/core/execution/TestDeciderOutcomes.java, core/src/test/java/com/netflix/conductor/core/execution/TestDeciderService.java, core/src/test/java/com/netflix/conductor/core/execution/TestWorkflowExecutor.java
----
Refactored task mapper to use string instead of task type.
=> task type refactoring.

common/src/main/java/com/netflix/conductor/common/metadata/events/EventHandler.java, core/src/main/java/com/netflix/conductor/core/events/SimpleActionProcessor.java, core/src/test/java/com/netflix/conductor/core/events/TestSimpleActionProcessor.java
add a boolean flag appendArray to append values to an array (default `true`)
=> 3.9.0 orkes f

postgres-persistence/src/main/java/com/netflix/conductor/postgres/config/PostgresConfiguration.java, postgres-persistence/src/main/java/com/netflix/conductor/postgres/config/PostgresProperties.java, server/src/main/resources/application.properties
=> Support for setting schema in postgres

core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java, core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
Mirror PR for https://github.com/Netflix/conductor/pull/3058
=> wait task parameterised support.

java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorker.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerExecutor.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/task/WorkerTask.java
=> Allow thread counts to be specified in the worker annotation

java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorker.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerExecutor.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/task/WorkerTask.java
Reverts orkes-io/conductor#139
=> Revert "Allow thread counts to be specified in the worker annotation"

core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java, core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
=> Orkes wait task fix 

build.gradle, client-spring/build.gradle, client-spring/src/main/java/com/netflix/conductor/client/spring/ConductorClientAutoConfiguration.java, client-spring/src/main/java/com/netflix/conductor/client/spring/ConductorWorkerAutoConfiguration.java, client-spring/src/main/java/com/netflix/conductor/client/spring/SpringWorkerConfiguration.java, client-spring/src/test/java/com/netflix/conductor/client/spring/Workers.java, client-spring/src/test/resources/application.properties, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/WorkflowExecutor.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorker.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerExecutor.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/NonRetryableException.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/TaskContext.java, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/executor/task/WorkerConfiguration.java, java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/executor/task/AnnotatedWorkerTests.java, java-sdk/src/test/java/com/netflix/conductor/sdk/workflow/executor/task/TestWorkerConfig.java
1. Add annotation support for pollingInterval
2. Allow configuration using spring
3. Tests
----
----
Issue #
----
=> use spring events to initialize workers and added tests

common/build.gradle, common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskType.java, common/src/main/java/com/netflix/conductor/common/metadata/workflow/EventType.java, common/src/main/java/com/netflix/conductor/common/metadata/workflow/TaskEvent.java, common/src/main/java/com/netflix/conductor/common/metadata/workflow/TaskEventList.java, common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java, common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java, core/src/main/java/com/netflix/conductor/core/execution/mapper/TaskMapperContext.java, core/src/main/java/com/netflix/conductor/model/TaskModel.java, core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java, grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java, grpc/src/main/proto/model/taskevent.proto, grpc/src/main/proto/model/taskeventlist.proto, grpc/src/main/proto/model/workflowdef.proto, grpc/src/main/proto/model/workflowtask.proto
Business state publish task.
More documents coming soon...
=> [Do not merge] Workflow state publish

core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
=> Setting reason for incompletion in case of workflow gets terminated

build.gradle, core/src/main/java/com/netflix/conductor/core/execution/mapper/SwitchTaskMapper.java, core/src/test/java/com/netflix/conductor/core/sync/local/LocalOnlyLockTest.java
----
- [ x] Feature
improve switch by adding inputs and selected case as output
----
Issue #
----
=> Switch task mapper

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java, grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java, grpc/src/main/proto/model/workflowtask.proto
----
- [x ] Feature
----
Issue #
----
=> add join status

core/src/main/java/com/netflix/conductor/core/execution/mapper/JoinTaskMapper.java
=> add joinStatus in the input

common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java, core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java, grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java, grpc/src/main/proto/model/workflowdef.proto, java-sdk/src/main/java/com/netflix/conductor/sdk/testing/LocalServerRunner.java, test-harness/src/test/groovy/com/netflix/conductor/test/integration/ExternalPayloadStorageSpec.groovy
----
----
* Fixed the issue that the last task in the workflow does not get the `executed` flag set
* Added a new property to store the status update sink
Issue #
----
=> Update task on complete

build.gradle, common/build.gradle, common/src/main/java/com/netflix/conductor/common/config/ObjectMapperProvider.java, java-sdk/build.gradle, java-sdk/src/main/java/com/netflix/conductor/sdk/workflow/utils/ObjectMapperProvider.java
----
- [x ] Feature
----
java time support and override for object mapper
Issue #
----
=> Object mapper override
